KUBE_POD = "pod"
KUBE_SERVICE = "svc"
KUBE_DEPLOYMENT = "deploy"
KUBE_REPLICASET = "rs"
KUBE_STATEFULSET = "sts"
KUBE_INGRESS = "ing"

ISTIO_GATEWAY = "gw"
ISTIO_VIRTUAL_SERVICE = "vs"
ISTIO_DESTINATION_RULE = "dr"

ALL_SHORTNAMES = [KUBE_POD, KUBE_SERVICE, KUBE_DEPLOYMENT, KUBE_REPLICASET, KUBE_STATEFULSET, KUBE_INGRESS,
    ISTIO_GATEWAY, ISTIO_VIRTUAL_SERVICE, ISTIO_DESTINATION_RULE]

#TODO shortname? really?