apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-A
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - path: /A
        pathType: Prefix
        backend:
          service:
            name: A.default.svc
            port:
              number: 80
