apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: F-timeout
  namespace: default
spec:
  http:
  - route:
    - destination:
        host: F.default.svc
    timeout: 2s
  hosts:
  - F.default.svc