apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: catalogue
spec:
  selector:
    matchLabels:
      service: catalogue # has to match .spec.template.metadata.labels
  serviceName: "nginx"
  replicas: 3 # by default is 1
  minReadySeconds: 10 # by default is 0
  template:
    metadata:
      labels:
        service: catalogue # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: S8-mysql-catalogue
        image: mysql-database:latest
        ports:
        - containerPort: 3306
          name: db-port
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "my-storage-class"
      resources:
        requests:
          storage: 1Gi