apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
  labels:
    service: store
spec:
  replicas: 1
  selector:
    matchLabels:
      service: store
  template:
    metadata:
      labels:
        service: store
    spec:
      containers:
      - name: S6-shop
        image: generic-image
        ports:
        - containerPort: 80
      - name: S5-e-commerce
        image: generic-image
        ports:
        - containerPort: 81
